uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
]
filtration_params:
  q_vel: 0.5
  q_pos: 0.1
  q_ori: 0.25
history_size: 2
fish_model_params:
  ALP0: 1
  ALP1: 0.09
  ALP2: 0
  BET0: 0.04
  BET1: 0.09
  BET2: 0
  GAM: 0.1
  R: 0.5
  V0: 1
  field_size: 1024

uav1:
  spawn:
    x: 0.0
    y: 0.0
    z: 2.0
    heading: 0

uav2:
  spawn:
    x: 4.0
    y: 0.0
    z: 2.0
    heading: 0

uav3:
  spawn:
    x: 0.0
    y: 4.0
    z: 2.0
    heading: 0

uav4:
  spawn:
    x: 0.0
    y: -4.0
    z: 2.0
    heading: 0

uav5:
  spawn:
    x: -4.0
    y: 0.0
    z: 2.0
    heading: 0

uav6:
  spawn:
    x: 4.0
    y: 4.0
    z: 2.0
    heading: 0

uav7:
  spawn:
    x: -4.0
    y: -4.0
    z: 2.0
    heading: 0

uav8:
  spawn:
    x: -4.0
    y: 4.0
    z: 2.0
    heading: 0

uav9:
  spawn:
    x: 4.0
    y: -4.0
    z: 2.0
    heading: 0

uav10:
  spawn:
    x: -8.0
    y: 0.0
    z: 2.0
    heading: 0